spring.application.name=app

spring.mongodb.uri=mongodb://localhost:27017/politicas_db
server.port=8080

jwt.secret=bWlfY2xhdmVfc3VwZXJfc2VjcmV0YV9kZV8zMl9jYXJhY3RlcmVz
jwt.expiration=86400000

app.aws.region=${AWS_REGION:us-east-2}
app.aws.s3.bucket=${AWS_S3_BUCKET:parcial1-files-dev-266671103534-us-east-2-an}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
gemini.api-key=AIzaSyDUMjMEU7voaXtyVopU-QfZzpVTl4ZWuQo
gemini.model=gemini-2.5-flash-lite