
# prod:
spring.application.name=app
server.port=${PORT:8080}

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.aws.region=${AWS_REGION}
app.aws.s3.bucket=${AWS_S3_BUCKET}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

gemini.api-key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash-lite}

