

# prod:
spring.application.name=app
server.port=${PORT:8080}

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.aws.region=${AWS_REGION}
app.aws.s3.bucket=${AWS_S3_BUCKET}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

gemini.api-key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash-lite}


# desa:
# spring.application.name=app
# server.port=8080

# spring.mongodb.uri=mongodb://localhost:27017/politicas_db
# spring.mongodb.database=politicas_db

# jwt.secret=bWlfY2xhdmVfc3VwZXJfc2VjcmV0YV9kZV8zMl9jYXJhY3RlcmVz
# jwt.expiration=86400000

# app.aws.region=us-east-2
# app.aws.s3.bucket=parcial1-files-dev-266671103534-us-east-2-an

# spring.servlet.multipart.max-file-size=20MB
# spring.servlet.multipart.max-request-size=25MB

# gemini.api-key=AIzaSyC9u_lrfwElDKfYv-dHgFJyBJxabrE-h8k
# gemini.model=gemini-2.5-flash-lite